import React, { useState, useEffect } from "react";
import "./../css/Login.css";
import Modal from 'react-modal';
import { BiFirstPage, BiLastPage, BiChevronLeft, BiChevronRight, BiX } from 'react-icons/bi';
import { login } from "../service/AuthenticationService";

import { useHistory, Redirect, Link } from 'react-router-dom';

import Cookies from "universal-cookie";
const cookies = new Cookies();

function Login() {


    useEffect(() => {
    }, []);

    return (
        <div>
            <p>POL&Iacute;TICA DE PRIVACIDADE DA OPT</p>
<p>1. RESPONS&Aacute;VEL DO TRATAMENTO</p>
<p>O respons&aacute;vel do tratamento dos seus dados em virtude desta Pol&iacute;tica de Privacidade &eacute;:</p>
<p>Nome: Arlindo de Jesus Louren&ccedil;o</p>
<p>NIPC: 123456789</p>
<p>Morada:</p>
<p>Rua: Rua 38, n&ordm; 394</p>
<p>C&oacute;digo Postal: 4500-332</p>
<p>Localidade: Espinho</p>
<p>Pa&iacute;s: Portugal</p>
<p>Contacto Eletr&oacute;nico: arlindo@opt.com</p>
<p>Telefone: 969 181 827</p>
<p>Cargo: Administrador e Respons&aacute;vel pela Recolha e Tratamento de Informa&ccedil;&atilde;o da OPT</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>A OPT reconhecemos a import&acirc;ncia de proteger a sua informa&ccedil;&atilde;o pessoal e comprometemo-nos a trat&aacute;-la com responsabilidade e em conformidade com as leis de prote&ccedil;&atilde;o de dados.</p>
<p>A presente pol&iacute;tica de privacidade pretende regular todos os aspetos relativos ao tratamento de dados dos diferentes usu&aacute;rios que navegam ou fornecem os seus dados pessoais atrav&eacute;s dos diferentes formul&aacute;rios situados na p&aacute;gina online.</p>
<p>&nbsp;</p>
<p>2. DADOS PESSOAIS</p>
<p>Um dado pessoal &eacute; a informa&ccedil;&atilde;o que o identifica ou que o torna identific&aacute;vel. Atrav&eacute;s da p&aacute;gina online, recolhemos os dados pessoais que o usu&aacute;rio nos comunica: Nomes, apelidos, correio eletr&oacute;nico, data de nascimento, etc. assim como todos os dados que sejam proporcionados de forma volunt&aacute;ria atrav&eacute;s de qualquer uma das redes sociais nas quais o usu&aacute;rio est&aacute; registado. Neste caso, a privacidade depender&aacute; da pr&oacute;pria configura&ccedil;&atilde;o estabelecida pelo usu&aacute;rio, assim como dos termos e condi&ccedil;&otilde;es da pr&oacute;pria rede social.</p>
<p>A visita do usu&aacute;rio &agrave; p&aacute;gina online n&atilde;o implica que tenha de facilitar informa&ccedil;&atilde;o sobre os seus dados pessoais. N&atilde;o obstante, caso os facilite, os dados ser&atilde;o tratados de forma l&iacute;cita de acordo com os princ&iacute;pios e direitos recolhidos no Regulamento (UE) 2016/679, de 27 de abril (Regulamento Geral sobre a Prote&ccedil;&atilde;o de Dados).</p>
<p>3. FINALIDADE, DURA&Ccedil;&Atilde;O E LEGITIMA&Ccedil;&Atilde;O DO TRATAMENTO</p>
<p>Os dados que o usu&aacute;rio nos proporcione ser&atilde;o tratados com as seguintes finalidades:</p>
<p>&bull; Registar-se no website atrav&eacute;s do formul&aacute;rio de registo situado na p&aacute;gina online que permitir&aacute; ao usu&aacute;rio aceder a informa&ccedil;&atilde;o mais detalhada disponibilizada pela OPT. Estes dados ser&atilde;o conservados at&eacute; que o usu&aacute;rio solicite o cancelamento do seu registo e durante o tempo estabelecido por lei com uma dura&ccedil;&atilde;o m&iacute;nima de 3 anos. A base de legitima&ccedil;&atilde;o do tratamento dos dados ser&aacute; o consentimento que outorga o usu&aacute;rio ao registar-se atrav&eacute;s do formul&aacute;rio de registo e ao selecionar a checkbox de aceita&ccedil;&atilde;o da nossa pol&iacute;tica de privacidade antes de enviar a sua solicitude. O usu&aacute;rio tem o direito de revogar o seu consentimento a qualquer momento sem que isso afete a licitude do tratamento baseado no consentimento pr&eacute;vio &agrave; sua retirada.</p>
<p>&bull; Dados de localiza&ccedil;&atilde;o: recolhemos dados de localiza&ccedil;&atilde;o exata ou aproximada atrav&eacute;s dos dispositivos m&oacute;veis dos utilizadores, se estes o tiverem permitido. A OPT apenas recolhe estes dados quando o website estiver aberto em primeiro plano. Contudo os utilizadores podem utilizar os servi&ccedil;os da OPT sem permitir que esta recolha os dados de localiza&ccedil;&atilde;o dos respetivos dispositivos m&oacute;veis. No entanto, tal pode afetar algumas funcionalidades dispon&iacute;veis. Por exemplo, se um utilizador n&atilde;o tiver autorizado a recolha dos dados de localiza&ccedil;&atilde;o, ter&aacute; de introduzir manualmente a localiza&ccedil;&atilde;o atual, para que possa ser identificada a paragem mais pr&oacute;xima.</p>
<p>&nbsp;</p>
<p>4. TRANSFER&Ecirc;NCIA OU COMUNICA&Ccedil;&Atilde;O DE DADOS PESSOAIS E TRANSFER&Ecirc;NCIAS INTERNACIONAIS</p>
<p>Os seus dados n&atilde;o ser&atilde;o comunicados ou transferidos a terceiros, a menos que haja alguma obriga&ccedil;&atilde;o legal ou aqueles fornecedores vinculados &agrave; Parte Respons&aacute;vel que atuam como encarregados do tratamento.</p>
<p>Nenhuma transfer&ecirc;ncia internacional &eacute; feita e caso em algum momento possam ser realizadas, ser&aacute; contactado com objetivo de obter o seu consentimento.</p>
<p>5. ACTUALIZA&Ccedil;&Atilde;O DE DADOS</p>
<p>&Eacute; importante que, para mantermos os dados pessoais atualizados, o usu&aacute;rio nos informe sempre que houver alguma modifica&ccedil;&atilde;o nos mesmos, caso contr&aacute;rio, n&atilde;o seremos respons&aacute;veis pela sua veracidade.</p>
<p>O usu&aacute;rio garante que os dados pessoais fornecidos s&atilde;o verdadeiros, garantindo que todas as informa&ccedil;&otilde;es fornecidas correspondem &agrave; situa&ccedil;&atilde;o real, atualizada e precisa, sendo obrigados a comunicar quaisquer altera&ccedil;&otilde;es.</p>
<p>6. DADOS DE TERCEIROS</p>
<p>Se o usu&aacute;rio fornecer dados de terceiros para qualquer finalidade &agrave; OPT garante que obteve esses dados de maneira legal, que informou previamente os afetados, obtendo seu consentimento para comunic&aacute;-los e que as informa&ccedil;&otilde;es fornecidas s&atilde;o precisas e verdadeiras.</p>
<p>7. CAR&Aacute;TER OBRIGAT&Oacute;RIO DA INFORMA&Ccedil;&Atilde;O SOLICITADA</p>
<p>Todos os nossos formul&aacute;rios t&ecirc;m um asterisco (*) nos dados obrigat&oacute;rios. Se o usu&aacute;rio n&atilde;o fornecer esses campos ou n&atilde;o marcar a caixa de aceita&ccedil;&atilde;o da pol&iacute;tica de privacidade, o envio das informa&ccedil;&otilde;es n&atilde;o ser&aacute; permitido.</p>
<p>8. USO DE PASSWORDS</p>
<p>Para aceder a informa&ccedil;&otilde;es mais detalhadas de servi&ccedil;os fornecidos pela OPT, o utilizador deve efetuar "Login" e incluir o endere&ccedil;o de e-mail e a password gerados no formul&aacute;rio de registo, de acordo com as regras de complexidade.</p>
<p>Os usu&aacute;rios s&atilde;o respons&aacute;veis pela cust&oacute;dia e confidencialidade adequadas de qualquer um dos identificadores e/ou passwords que selecionaram no registo e comprometem-se a n&atilde;o atribuir seu uso a terceiros, nem permitir o acesso a terceiros.</p>
<p>Da mesma forma, ser&aacute; obriga&ccedil;&atilde;o do usu&aacute;rio notificar imediatamente o Respons&aacute;vel sobre qualquer evento que permita o uso indevido de identificadores e/ou senhas, como roubo, perda ou acesso n&atilde;o autorizado a eles, a fim de prosseguir com o seu cancelamento imediato.</p>
<p>9. DIREITOS DOS INTERESSADOS</p>
<p>Os utilizadores t&ecirc;m direito a aceder aos seus dados e obter confirma&ccedil;&atilde;o sobre seu tratamento, bem como uma c&oacute;pia dos dados pessoais sujeitos ao processamento. Os utilizadores t&ecirc;m direito de atualiz&aacute;-los e solicitar a retifica&ccedil;&atilde;o dos dados imprecisos ou solicitar a exclus&atilde;o quando os dados n&atilde;o forem necess&aacute;rios para os fins para os quais foram recolhidos.</p>
<p>Os utilizadores podem solicitar a limita&ccedil;&atilde;o no processamento dos seus dados e podem opor-se ao processamento, revogando o seu consentimento, al&eacute;m de exercer o direito &agrave; portabilidade de dados. Da mesma forma, t&ecirc;m o direito de n&atilde;o estar sujeito a decis&otilde;es baseadas apenas no processamento automatizado dos seus dados pessoais. Pode exercer os seus direitos entrando em contacto connosco pelo e-mail: privacy@opt.pt. Se um utilizador considerar que os seus direitos n&atilde;o foram devidamente tratados, tem o direito de registar uma reclama&ccedil;&atilde;o junto &agrave; autoridade supervisora em www.aepd.pt.</p>
<p>10. TRATAMENTO DE DADOS DE MENORES DE IDADE</p>
<p>Quem facilita os dados atrav&eacute;s dos formul&aacute;rios deste website e aceita seu tratamento declara ter mais de 13 anos, sendo proibido o acesso e uso do portal a menores de idade. Se a qualquer momento, o Respons&aacute;vel detetar que uma crian&ccedil;a menor de 13 anos forneceu dados pessoais, procederemos ao cancelamento dos mesmos.</p>
<p>Da mesma forma, pais ou respons&aacute;veis podem, em qualquer caso, entrar em contacto com a OPT para bloquear a conta de acesso de menores sob seus cuidados que se registaram falsificando sua identidade.</p>
<p>Se a idade for inferior &agrave; idade m&iacute;nima obrigat&oacute;ria &eacute; necess&aacute;rio uma autoriza&ccedil;&atilde;o de um dos pais ou do tutor legal para utilizar os servi&ccedil;os da OPT. Para isso, o tutor legal deve ler os presentes termos consigo.</p>
<p>Se for pai/m&atilde;e ou tutor legal de uma crian&ccedil;a e autorizar que a mesma utilize os servi&ccedil;os, os presentes termos aplicam-se a si, sendo respons&aacute;vel pela atividade da crian&ccedil;a nos servi&ccedil;os.</p>
<p>12. TRATAMENTO DE COOKIES</p>
<p>Uma cookie &eacute; um pequeno arquivo descarregado e armazenado no computador do usu&aacute;rio quando ele acede uma p&aacute;gina online. As cookies permitem que a p&aacute;gina online, entre outras coisas, armazene e recupere informa&ccedil;&otilde;es sobre os h&aacute;bitos de navega&ccedil;&atilde;o do usu&aacute;rio ou dos</p>
<p>seus equipamentos e, dependendo das informa&ccedil;&otilde;es que eles cont&ecirc;m e da maneira como usam os seus equipamentos, podem ser usados para reconhecer o usu&aacute;rio.</p>
<p>O usu&aacute;rio tem a op&ccedil;&atilde;o de impedir a gera&ccedil;&atilde;o de cookies ao selecionar a op&ccedil;&atilde;o correspondente no seu programa de navegador.</p>
<p>&nbsp;</p>
<p>Data de atualiza&ccedil;&atilde;o: 17/12/2020</p>

<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 1">Termos&nbsp;</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 1">d</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 1">e&nbsp;</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 1">Utiliza&ccedil;&atilde;o&nbsp;</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 1">da</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 1">&nbsp;OPT</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:240,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 2">1.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 2">Disposi&ccedil;&otilde;es gerais&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="7" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">Estes Termos e Condi&ccedil;&otilde;es juntamente com a Pol&iacute;tica de Privacidade e qualquer outra documenta&ccedil;&atilde;o do Website destinam-se a fornecer informa&ccedil;&otilde;es sobre a Rede de Autocarros Paredes (</span><span data-contrast="auto">OPT</span><span data-contrast="auto">).</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="7" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">Nenhuma&nbsp;</span><span data-contrast="auto">a&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;estar&aacute; dispon&iacute;vel&nbsp;</span><span data-contrast="auto">at&eacute;</span><span data-contrast="auto">&nbsp;que&nbsp;</span><span data-contrast="auto">o utilizador crie uma nova conta, sendo necess&aacute;rio aceitar os</span><span data-contrast="auto">&nbsp;Termos e Condi&ccedil;&otilde;es e a Pol&iacute;tica de</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">Privacidade</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 2">2.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 2">Aplicabilidade dos Termos e Condi&ccedil;&otilde;es&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">2.1</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Contas de Utilizadores&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="8" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">O utilizador&nbsp;</span><span data-contrast="auto">que pretende aceder a todos os Servi&ccedil;os fornecidos no Website deve registar-se e criar uma Conta. O registo&nbsp;</span><span data-contrast="auto">&eacute; efetuado&nbsp;</span><span data-contrast="auto">atrav&eacute;s do preenchimento de todas as informa&ccedil;&otilde;es necess&aacute;rias no formul&aacute;rio de registo que pode ser encontrado no Website.&nbsp;</span><span data-contrast="auto">O utilizador&nbsp;</span><span data-contrast="auto">ter&aacute; de</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">introduzir&nbsp;</span><span data-contrast="auto">o seu nome de utilizador, endere&ccedil;o de correio&nbsp;</span><span data-contrast="auto">eletr&oacute;nico</span><span data-contrast="auto">, palavra-passe</span><span data-contrast="auto">,&nbsp;</span><span data-contrast="auto">TODO</span><span data-contrast="auto">. Para completar o registo, a pessoa ter&aacute; de aceitar os Termos e Condi&ccedil;&otilde;es e a Pol&iacute;tica de Privacidad</span><span data-contrast="auto">e</span><span data-contrast="auto">. A falta de fornecimento de qualquer informa&ccedil;&atilde;o que, a crit&eacute;rio exclusivo d</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">, seja necess&aacute;ria para verificar qualquer novo utilizador (independentemente de tal informa&ccedil;&atilde;o ser exigida nestes Termos e Condi&ccedil;&otilde;es), &eacute; considerada motivo de recusa de prosseguir com o registo.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="8" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">A qualquer momento, se&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">considerar que a Conta corre um risco elevado de causar danos a qualquer pessoa,&nbsp;</span><span data-contrast="auto">a OPT&nbsp;</span><span data-contrast="auto">tem&nbsp;</span><span data-contrast="auto">o&nbsp;</span><span data-contrast="auto">direito de suspender a utiliza&ccedil;&atilde;o da Conta, restringindo o acesso&nbsp;</span><span data-contrast="auto">a esta</span><span data-contrast="auto">. Ap&oacute;s o risco ser eliminado,&nbsp;</span><span data-contrast="auto">a OPT&nbsp;</span><span data-contrast="auto">deve&nbsp;</span><span data-contrast="auto">reativar</span><span data-contrast="auto">&nbsp;a Conta. Na situa&ccedil;&atilde;o em que o gestor de uma Conta viole a lei ou estes Termos e Condi&ccedil;&otilde;es,&nbsp;</span><span data-contrast="auto">a OPT&nbsp;</span><span data-contrast="auto">tem o direito de bloquear a Conta.&nbsp;</span><span data-contrast="auto">A</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OTP&nbsp;</span><span data-contrast="auto">ter&aacute; o direito de suspender ou bloquear a utiliza&ccedil;&atilde;o da Conta desde que ocorram quaisquer outras circunst&acirc;ncias que possam resultar em risco para qualquer pessoa ou viola&ccedil;&atilde;o da lei.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="8" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;s&atilde;o respons&aacute;veis pelo cuidado razo&aacute;vel da Conta e devem assegurar-se de que o endere&ccedil;o de correio&nbsp;</span><span data-contrast="auto">eletr&oacute;nico</span><span data-contrast="auto">&nbsp;est&aacute;&nbsp;</span><span data-contrast="auto">atualizado</span><span data-contrast="auto">.&nbsp;</span><span data-contrast="auto">A</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OPT&nbsp;</span><span data-contrast="auto">n&atilde;o &eacute; respons&aacute;vel pelas situa&ccedil;&otilde;es em que os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;n&atilde;o recebam informa&ccedil;&otilde;es devido &agrave; sua neglig&ecirc;ncia.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="8" data-aria-posinset="4" data-aria-level="1"><span data-contrast="auto">Na situa&ccedil;&atilde;o em que&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;decide que o Website deve ser modernizado ou est&aacute; com problemas t&eacute;cnicos,&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;tem o direito de restringir a possibilidade de entrar na Conta ou de utilizar os&nbsp;</span><span data-contrast="auto">respetivos</span><span data-contrast="auto">&nbsp;Servi&ccedil;os ou mesmo o acesso geral ao Website.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p>Page Break<span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="8" data-aria-posinset="5" data-aria-level="1"><span data-contrast="auto">Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;reconhecem que dar qualquer informa&ccedil;&atilde;o sobre a sua Conta pode causar danos&nbsp;</span><span data-contrast="auto">&agrave;</span><span data-contrast="auto">&nbsp;OPT</span><span data-contrast="auto">&nbsp;ou a terceiros. S&atilde;o respons&aacute;veis por assegurar esse tipo de informa&ccedil;&atilde;o e, caso n&atilde;o o fa&ccedil;am, os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;s&atilde;o respons&aacute;veis pela elimina&ccedil;&atilde;o de todos os danos causados.&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="8" data-aria-posinset="6" data-aria-level="1"><span data-contrast="auto">O&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;n&atilde;o dever&aacute; utilizar outras contas e n&atilde;o colocar&aacute; as suas contas &agrave; disposi&ccedil;&atilde;o de outros&nbsp;</span><span data-contrast="auto">(</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;ou de terceiros</span><span data-contrast="auto">)</span><span data-contrast="auto">. A&nbsp;</span><span data-contrast="auto">exce&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;&agrave; regra da presente Sec&ccedil;&atilde;o acima mencionada ser&aacute; a de permitir que quaisquer&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;devidamente autorizad</span><span data-contrast="auto">o</span><span data-contrast="auto">s do&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;possam agir em nome d</span><span data-contrast="auto">este</span><span data-contrast="auto">. No entanto, todas as responsabilidades por&nbsp;</span><span data-contrast="auto">a&ccedil;&otilde;es</span><span data-contrast="auto">&nbsp;e resultados de pessoas que tiveram acesso &agrave;s contas do&nbsp;</span><span data-contrast="auto">respetivo</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;ser&atilde;o assumidas pelo&nbsp;</span><span data-contrast="auto">respetivo</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">4.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Termos e condi&ccedil;&otilde;es de utiliza&ccedil;&atilde;o&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="9" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">Em conformidade com estes Termos e Condi&ccedil;&otilde;es,&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;concede aos&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;uma licen&ccedil;a limitada, n&atilde;o exclusiva, n&atilde;o transfer&iacute;vel e n&atilde;o public&aacute;vel para aceder e fazer uso pessoal e n&atilde;o comercial dos Servi&ccedil;os prestados. Tal licen&ccedil;a &eacute; estritamente limitada &agrave;s funcionalidades do Website.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="9" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;s&atilde;o obrigados a n&atilde;o abusar dos Servi&ccedil;os&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;e apenas a utiliz&aacute;-los conforme estabelecido por lei e pelos presentes Termos e Condi&ccedil;&otilde;es. A utiliza&ccedil;&atilde;o inapropriada dos Servi&ccedil;os pode causar efeitos negativos&nbsp;</span><span data-contrast="auto">na</span><span data-contrast="auto">&nbsp;OPT</span><span data-contrast="auto">&nbsp;ou a terceiros</span><span data-contrast="auto">.</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">S</span><span data-contrast="auto">e os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;violarem a utiliza&ccedil;&atilde;o dos Servi&ccedil;os, s&atilde;o respons&aacute;veis pela elimina&ccedil;&atilde;o de todos os danos causados.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="9" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">Todos os direitos d</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;ou dos seus licenciadores, fornecedores, propriet&aacute;rios ou outras pessoas est&atilde;o protegidos, mesmo que n&atilde;o seja expressamente concedido nestes Termos e Condi&ccedil;&otilde;es.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="9" data-aria-posinset="4" data-aria-level="1"><span data-contrast="auto">Qualquer&nbsp;</span><span data-contrast="auto">objeto</span><span data-contrast="auto">&nbsp;de propriedade intelectual no Website, com&nbsp;</span><span data-contrast="auto">exce&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;daqueles carregados, transmitidos, disponibilizados, publicados pelos&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">, bem como a&nbsp;</span><span data-contrast="auto">sele&ccedil;&atilde;o</span><span data-contrast="auto">, organiza&ccedil;&atilde;o, coordena&ccedil;&atilde;o, compila&ccedil;&atilde;o dos materiais e o esbo&ccedil;o geral e a natureza do Website constituem propriedade intelectual d</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">. S&atilde;o protegidos por direitos de autor, marcas registadas, patentes, direitos de desenho industrial e quaisquer outros direitos e disposi&ccedil;&otilde;es, incluindo conven&ccedil;&otilde;es internacionais e direitos de propriedade.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="9" data-aria-posinset="5" data-aria-level="1"><span data-contrast="auto">Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;s&atilde;o obrigados a ler e aceitar os Termos e Condi&ccedil;&otilde;es e a Pol&iacute;tica de Privacidade, bem como qualquer outra documenta&ccedil;&atilde;o do Website, para assegurar a&nbsp;</span><span data-contrast="auto">prote&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;dos seus dados pessoais. Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;comprometem-se a realizar quaisquer&nbsp;</span><span data-contrast="auto">a&ccedil;&otilde;es</span><span data-contrast="auto">&nbsp;poss&iacute;veis para n&atilde;o entrar em situa&ccedil;&atilde;o de viola&ccedil;&atilde;o da&nbsp;</span><span data-contrast="auto">prote&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;de dados pessoais.&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p>Page Break<span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="9" data-aria-posinset="6" data-aria-level="1"><span data-contrast="auto">Os Utilizadores&nbsp;</span><span data-contrast="auto">confirma</span><span data-contrast="auto">m&nbsp;</span><span data-contrast="auto">e declara</span><span data-contrast="auto">m&nbsp;</span><span data-contrast="auto">que:</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o anunciar&atilde;o qualquer informa&ccedil;&atilde;o impr&oacute;pria ou defeituosa que possa ser prejudicial&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">, a outros&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;ou a terceiras pessoas.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o ir&atilde;o carregar ou divulgar qualquer informa&ccedil;&atilde;o no Website que possa violar leis, acordos contratuais ou direitos de terceiros. Tais informa&ccedil;&otilde;es violadoras poder&atilde;o ser material com direitos de autor, dados pessoais, segredos comerciais e outros.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">N&atilde;o fornecer</span><span data-contrast="auto">&atilde;o</span><span data-contrast="auto">&nbsp;qualquer informa&ccedil;&atilde;o falsa que possa induzir em erro outros Utilizadores.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="4" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o tentar</span><span data-contrast="auto">&atilde;o&nbsp;</span><span data-contrast="auto">invadir, modificar, desativar, ou afetar de qualquer outra forma o Website ou desafiar a sua seguran&ccedil;a.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="5" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o utilizar</span><span data-contrast="auto">&atilde;o&nbsp;</span><span data-contrast="auto">o Website para qualquer outro fim que n&atilde;o seja o de ser utilizado tendo em conta os&nbsp;</span><span data-contrast="auto">objetivos</span><span data-contrast="auto">&nbsp;dos Servi&ccedil;os&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="6" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o tentar</span><span data-contrast="auto">&atilde;o</span><span data-contrast="auto">&nbsp;recolher quaisquer dados pessoais que estejam a ser mantidos no sistema do Website e n&atilde;o ofender&aacute; ou enganar&aacute; outros&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="7" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o utilizar&aacute; o Website para quaisquer fins ilegais ou para violar quaisquer leis.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="3" data-aria-posinset="8" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o tentar&aacute; interferir com a&nbsp;</span><span data-contrast="auto">atividade</span><span data-contrast="auto">&nbsp;do Website ou proibir outros&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;de utilizar o Website (ou dificultar a sua utiliza&ccedil;&atilde;o).</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">5.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Obriga&ccedil;&otilde;es da&nbsp;</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">OPT</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="10" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">A&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;cooperar&aacute; com os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;no que diz respeito a todas as quest&otilde;es relacionadas com a presta&ccedil;&atilde;o adequada de Servi&ccedil;os. A comunica&ccedil;&atilde;o entre&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;e&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;ser&aacute; feita atrav&eacute;s de correio&nbsp;</span><span data-contrast="auto">eletr&oacute;nico</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="10" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">A&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;prestar&aacute; apoio t&eacute;cnico aos&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">quando&nbsp;</span><span data-contrast="auto">que estes se deparem com quaisquer problemas em rela&ccedil;&atilde;o &agrave; funcionalidade da Conta e do Website.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">6.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Obriga&ccedil;&otilde;es dos&nbsp;</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Utilizadores</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="11" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;concordam e reconhecem</span><span data-contrast="auto">&nbsp;que</span><span data-contrast="auto">:&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="4" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">C</span><span data-contrast="auto">oncordam com os Termos e Condi&ccedil;&otilde;es e Pol&iacute;tica de Privacidade, bem como com quaisquer outros documentos do Website.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="4" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o&nbsp;</span><span data-contrast="auto">atuar&atilde;o</span><span data-contrast="auto">&nbsp;de uma forma que possa ter efeitos negativos para&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">, outros&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;ou terceiros, em resultado de danos causados, deteriora&ccedil;&atilde;o da reputa&ccedil;&atilde;o, etc.&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="4" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o utilizar os servi&ccedil;os&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;no Website ou no pr&oacute;prio Website com fins ilegais ou de outra forma que n&atilde;o seja aceit&aacute;vel.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="4" data-aria-posinset="4" data-aria-level="1"><span data-contrast="auto">N</span><span data-contrast="auto">&atilde;o tomar&atilde;o quaisquer&nbsp;</span><span data-contrast="auto">a&ccedil;&otilde;es</span><span data-contrast="auto">&nbsp;que possam violar leis, Termos e Condi&ccedil;&otilde;es, Pol&iacute;tica de Privacidade ou outros documentos.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="4" data-aria-posinset="5" data-aria-level="1"><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">7.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Responsabilidade&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="12" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">Se</span><span data-contrast="auto">&nbsp;a</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;n&atilde;o cumprir estes Termos e Condi&ccedil;&otilde;es, &eacute; respons&aacute;vel por perdas ou danos que o&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;sofra e que result</span><span data-contrast="auto">em&nbsp;</span><span data-contrast="auto">d</span><span data-contrast="auto">a</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">viola&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">destes Termos e Condi&ccedil;&otilde;es ou neglig&ecirc;ncia&nbsp;</span><span data-contrast="auto">da&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">, mas</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">n&atilde;o ser&aacute; respons&aacute;vel por qualquer perda ou dano que n&atilde;o seja previs&iacute;vel. As perdas ou danos s&atilde;o previs&iacute;veis se forem uma consequ&ecirc;ncia &oacute;bvia da viola&ccedil;&atilde;o d</span><span data-contrast="auto">os termos deste documento</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">8.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Eventos Fora do controlo&nbsp;</span></span></strong><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">da OPT</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="13" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">A</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;n&atilde;o ser&aacute; respons&aacute;vel por qualquer falha ou atraso no cumprimento de qualquer&nbsp;</span><span data-contrast="auto">obriga&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">ao abrigo destes Termos e Condi&ccedil;&otilde;es que seja causada por um Evento Fora do Contro</span><span data-contrast="auto">lo</span><span data-contrast="auto">&nbsp;OPT</span><span data-contrast="auto">.&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="13" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">Um Evento Fora do Control</span><span data-contrast="auto">o da</span><span data-contrast="auto">&nbsp;OPT</span><span data-contrast="auto">&nbsp;significa qualquer&nbsp;</span><span data-contrast="auto">ato</span><span data-contrast="auto">&nbsp;ou evento&nbsp;</span><span data-contrast="auto">que n&atilde;o depende diretamente da</span><span data-contrast="auto">&nbsp;OP</span><span data-contrast="auto">T</span><span data-contrast="auto">, incluindo lock-outs ou outra&nbsp;</span><span data-contrast="auto">a&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;industrial de terceiros, como&ccedil;&atilde;o civil, motim, invas&atilde;o, ataque terrorista ou amea&ccedil;a de ataque terrorista, guerra (declarada ou n&atilde;o) ou amea&ccedil;a ou prepara&ccedil;&atilde;o para a guerra, inc&ecirc;ndio, explos&atilde;o, tempestade, inunda&ccedil;&atilde;o, terramoto, subsid&ecirc;ncia, epidemia ou outra cat&aacute;strofe natural, ou falha das redes de telecomunica&ccedil;&otilde;es p&uacute;blicas ou privadas ou impossibilidade de utiliza&ccedil;&atilde;o dos caminhos-de-ferro, transporte mar&iacute;timo, a&eacute;reo, transporte motorizado ou outros meios de transporte p&uacute;blicos ou privados.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="13" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">Se ocorrer um Evento Fora do Control</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;que&nbsp;</span><span data-contrast="auto">afete</span><span data-contrast="auto">&nbsp;o cumprimento das obriga&ccedil;&otilde;es&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;ao abrigo destes Termos e Condi&ccedil;&otilde;es:&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="5" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">A&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;contactar&aacute; os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">afetados</span><span data-contrast="auto">&nbsp;logo que&nbsp;</span><span data-contrast="auto">seja</span><span data-contrast="auto">&nbsp;poss&iacute;vel notific</span><span data-contrast="auto">&aacute;</span><span data-contrast="auto">-lo</span><span data-contrast="auto">s</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="5" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">As obriga&ccedil;&otilde;es&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;ao abrigo destes Termos e Condi&ccedil;&otilde;es ser&atilde;o suspensas e o tempo para o cumprimento das obriga&ccedil;&otilde;es ser&aacute; prolongado durante&nbsp;</span><span data-contrast="auto">o per&iacute;odo de a&ccedil;&atilde;o</span><span data-contrast="auto">&nbsp;do Evento Fora do Control</span><span data-contrast="auto">o</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">9.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Reclama&ccedil;&otilde;es&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="14" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">Se os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;tiverem sofrido qualquer viola&ccedil;&atilde;o dos seus direitos causada pelos Servi&ccedil;os&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;fornecidos nos Termos e Condi&ccedil;&otilde;es e/ou na Pol&iacute;tica de Privacidade, t&ecirc;m o direito de apresentar uma queixa. A queixa deve ser enviada&nbsp;</span><span data-contrast="auto">&agrave; OPT&nbsp;</span><span data-contrast="auto">por correio&nbsp;</span><span data-contrast="auto">eletr&oacute;nico</span><span data-contrast="auto">, que &eacute; especificado na Sec&ccedil;&atilde;o 11.&nbsp;</span><span data-contrast="auto">A</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;envida os seus melhores esfor&ccedil;os para que todas as queixas sejam resolvidas no prazo de 14 (catorze) dias ap&oacute;s a sua&nbsp;</span><span data-contrast="auto">rece&ccedil;&atilde;o</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="14" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">A queixa deve fornecer esta informa&ccedil;&atilde;o:&nbsp;</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="6" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">Quais os direitos que foram violados.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="6" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">Descri&ccedil;&atilde;o das circunst&acirc;ncias sob as quais os direitos foram violados.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="14" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">Qualquer disputa, controv&eacute;rsia, ou reclama&ccedil;&atilde;o, decorrente ou relacionada com estes Termos e Condi&ccedil;&otilde;es, a sua viola&ccedil;&atilde;o, rescis&atilde;o ou validade ser&aacute; finalmente resolvida no&nbsp;</span><span data-contrast="auto">respetivo</span><span data-contrast="auto">&nbsp;tribunal de Portugal sujeito &agrave;s regras de jurisdi&ccedil;&atilde;o.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">10.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Rescis&atilde;o&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="17" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">O&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;pode rescindir o acordo com&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;retirando a sua conta do Website. Isto pode ser feito atrav&eacute;s da apresenta&ccedil;&atilde;o do pedido no sistema da sua Conta.&nbsp;</span><span data-contrast="auto">A OPT&nbsp;</span><span data-contrast="auto">elimina a Conta no prazo de 7 (sete) dias ap&oacute;s o dia em que o pedido foi apresentado. Durante este per&iacute;odo, o&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;tem o direito de cancelar a remo&ccedil;&atilde;o da Conta.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p>Page Break<span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="17" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">A</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;pode rescindir tal acordo, apagando a Conta do&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;ou bloqueando o seu acesso ao Website. O acesso pode ser bloqueado se existirem quaisquer suspeitas de&nbsp;</span><span data-contrast="auto">a&ccedil;&otilde;es</span><span data-contrast="auto">&nbsp;ilegais e pode durar at&eacute; que as circunst&acirc;ncias desapare&ccedil;am ou sejam eliminadas.&nbsp;</span><span data-contrast="auto">A&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;elimina a Conta do&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;em situa&ccedil;&otilde;es em que este viole grosseiramente os Termos e Condi&ccedil;&otilde;es, Pol&iacute;tica de Privacidade, leis, ou outros documentos.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="17" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">Durante o per&iacute;odo de rescis&atilde;o do acordo, o&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;n&atilde;o pode criar outra Conta no Website.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<p><strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">11.</span></span></strong> <strong><span data-contrast="none"><span data-ccp-parastyle="heading 3">Disposi&ccedil;&otilde;es finais&nbsp;</span></span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559738&quot;:40}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">A Pol&iacute;tica de Privacidade e qualquer outra documenta&ccedil;&atilde;o do Website s&atilde;o parte integrante destes Termos e Condi&ccedil;&otilde;es e vinculam todas as contas registadas.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">Sem a permiss&atilde;o d</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">, os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;n&atilde;o t&ecirc;m o direito de transferir as suas obriga&ccedil;&otilde;es, reclama&ccedil;&otilde;es ou direitos a terceiros. Os&nbsp;</span><span data-contrast="auto">utilizadores</span><span data-contrast="auto">&nbsp;concordam que&nbsp;</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;ter&aacute; o direito de transferir os seus direitos e obriga&ccedil;&otilde;es decorrentes dos acordos a terceiros. O&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;informar&aacute; de tal transfer&ecirc;ncia por correio&nbsp;</span><span data-contrast="auto">eletr&oacute;nico</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="3" data-aria-level="1"><span data-contrast="auto">Se qualquer disposi&ccedil;&atilde;o destes Termos e Condi&ccedil;&otilde;es for considerada ilegal, inv&aacute;lida ou inaplic&aacute;vel por um tribunal ou tribunal arbitral, as outras disposi&ccedil;&otilde;es dos presentes Termos e Condi&ccedil;&otilde;es permanecer&atilde;o em pleno vigor e efeito. Qualquer disposi&ccedil;&atilde;o destes Termos e Condi&ccedil;&otilde;es considerada ilegal, inv&aacute;lida, ou inaplic&aacute;vel apenas em parte, ou em certo grau, permanecer&aacute; em pleno vigor e efeito na medida em que n&atilde;o seja considerada ilegal,&nbsp;</span><span data-contrast="auto">inv&aacute;lida ou inaplic&aacute;vel</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="4" data-aria-level="1"><span data-contrast="auto">Estes Termos e Condi&ccedil;&otilde;es e as rela&ccedil;&otilde;es entre</span><span data-contrast="auto">&nbsp;a</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">OPT</span><span data-contrast="auto">&nbsp;e&nbsp;</span><span data-contrast="auto">os&nbsp;</span><span data-contrast="auto">Utilizadores</span><span data-contrast="auto">&nbsp;(incluindo a execu&ccedil;&atilde;o, validade, invalidade, implementa&ccedil;&atilde;o e cessa&ccedil;&atilde;o destes Termos e Condi&ccedil;&otilde;es) s&atilde;o regidos e interpretados de acordo com as leis de Portugal.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="5" data-aria-level="1"><span data-contrast="auto">Salvo disposi&ccedil;&atilde;o em contr&aacute;rio nestes Termos e Condi&ccedil;&otilde;es, nenhum atraso d</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;ou do&nbsp;</span><span data-contrast="auto">Utilizador</span><span data-contrast="auto">&nbsp;no exerc&iacute;cio de qualquer direito ou no cumprimento de uma obriga&ccedil;&atilde;o ao abrigo destes Termos e Condi&ccedil;&otilde;es ser&aacute; considerado como uma ren&uacute;ncia a tal direito ou desculpa do cumprimento de tal obriga&ccedil;&atilde;o e o cumprimento separado ou parcial de qualquer obriga&ccedil;&atilde;o. O exerc&iacute;cio separado ou parcial de qualquer direito n&atilde;o significa que esta obriga&ccedil;&atilde;o n&atilde;o deva ser cumprida, ou que este direito n&atilde;o possa ser exercido no futuro.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="6" data-aria-level="1"><span data-contrast="auto">Todos os dados e informa&ccedil;&otilde;es armazenados no Website podem ser utilizados pel</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;de prop&oacute;sito para o seu funcionamento.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="7" data-aria-level="1"><span data-contrast="auto">A comunica&ccedil;&atilde;o com o apoi</span><span data-contrast="auto">a OPT</span><span data-contrast="auto">&nbsp;prossegue atrav&eacute;s do endere&ccedil;o&nbsp;</span><span data-contrast="auto">eletr&oacute;nico</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">privacy</span><span data-contrast="auto">@</span><span data-contrast="auto">opt</span><span data-contrast="auto">.</span><span data-contrast="auto">pt</span><span data-contrast="auto">.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></p>
<ol>
<li data-leveltext="%1." data-font="Lato" data-listid="18" data-aria-posinset="8" data-aria-level="1"><span data-contrast="auto">No caso dos Termos e Condi&ccedil;&otilde;es serem traduzidos para outras l&iacute;nguas e se houver diferen&ccedil;as entre a vers&atilde;o&nbsp;</span><span data-contrast="auto">portuguesa</span><span data-contrast="auto">&nbsp;e tal tradu&ccedil;&atilde;o, a vers&atilde;o&nbsp;</span><span data-contrast="auto">portuguesa</span><span data-contrast="auto">&nbsp;prevalecer&aacute;, salvo disposi&ccedil;&atilde;o em contr&aacute;rio.</span><span data-ccp-props="{&quot;134233279&quot;:true,&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559740&quot;:276}">&nbsp;</span></li>
</ol>
        </div>
    );
}

export default Login;