create or replace FUNCTION getActiveScooters RETURN SYS_REFCURSOR AS

    activeScooters SYS_REFCURSOR;
BEGIN
    OPEN activeScooters FOR SELECT v.DESCRIPTION_VEHICLE,v.WEIGHT,P.LATITUDE,P.LONGITUDE,V.AERODYNAMIC,V.FRONTAL_AREA,S.SCOOTER_TYPE,S.MAX_BATERY,S.ACTUAL_BATERY,S.MOTOR_POWER
    FROM VEHICLE V INNER JOIN SCOOTER S ON s.DESCRIPTION_VEHICLE = v.DESCRIPTION_VEHICLE
    INNER JOIN VEHICLES_LOCATION VL on V.DESCRIPTION_VEHICLE = VL.DESCRIPTION_VEHICLE
    INNER JOIN POINTS P on VL.DESCRIPTION_POINT = P.DESCRIPTION_POINT WHERE V.STATUS = 1;
    return activeScooters;
END;
/
