create or replace function getActiveVehicles RETURN SYS_REFCURSOR AS
    res SYS_REFCURSOR;
Begin
    OPEN res FOR Select v.DESCRIPTION_VEHICLE,v.WEIGHT,P.LATITUDE,P.LONGITUDE,v.AERODYNAMIC, v.FRONTAL_AREA FROM vehicle v
    INNER JOIN VEHICLES_LOCATION VL on v.DESCRIPTION_VEHICLE = VL.DESCRIPTION_VEHICLE
    INNER JOIN POINTS P on VL.DESCRIPTION_POINT = P.DESCRIPTION_POINT;
    Return res;
End;
/

